name: Build Original Language

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install dependencies (Flex, Bison, libfl)
      run: |
        sudo apt-get update
        sudo apt-get install -y flex bison g++ libfl-dev

    - name: Compile lexer and parser
      run: |
        bison -d limbaj.y
        flex -o lex.yy.c limbaj.l

    - name: Build final executable
      run: |
        g++ -o language limbaj.tab.c lex.yy.c SymTable.cpp -lfl

    - name: Run sample test (optional)
      run: |
        echo 'Running language with test input (if exists)...'
        if [ -f test.input ]; then
          ./language < test.input
        else
          echo "No test.input file found"
        fi
